[package]
name = "dmesg-to-json"
version = "0.1.0"
authors = ["Christian C. <x10an14@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rmesg = "0.8.0"
